name: Tests CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: |
          yarn install

      - name: Runs tests
        run: |
          yarn test-ci

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
